### ISSUE TITLE
能否加个debug日志，不然只是一个白屏，也不知道是可以ctrl+c退出，还是继续等

### ISSUE THREAD

**Issue by helloworldtang** [virjar/dungproxy#2]
使用的是com.virjar.dungproxy.webmagic7.DungProxyDownloader。

疑问2：   

如果进行如下配置，是否就不需要proxyclient.properties这个文件了。但没有这个文件，log中又会打印一个warn

'''java
        DungProxyDownloader downloader = new DungProxyDownloader();
        DungProxyProvider dungProxyProvider = new DungProxyProvider("www.dytt8.net",
                "http://www.dytt8.net/index.htm",
                (page, avProxy) -> {
                    if (!page.isDownloadSuccess() && StringUtils.contains(page.getRawText(), "IP暂时不能访问")) {
                        avProxy.block(BLOCK_TIME_STAMP_24HOUR);
                    }
                    return false;
                });

        //设置动态转发代理，使用定制的ProxyProvider
        downloader.setProxyProvider(dungProxyProvider);

```

**Comment by virjar** [comment]
1. proxyclient.properties的使用方式，确实是我考虑不周到，前期为了方便使用配置文件的方式实现扩展和定制，但是到后期发现很多扩展功能并不能单纯的使用配置文件来描述。所以我后来做了一次重构，主要提供javaAPI的方式，同时为了兼容，也将配置文件的的功能转移到来javaAPI。

因为很多同学使用了配置文件的方案，但是他们经常配置文件地址没有放对，所以我在这里打印了一个日志，目的是当配置文件不能加载的时候，打印出预期的文件位置。方便使用配置文件方案的同学排查问题。

现在有3个方案：1.完全废弃叫配置文件。 2.将日志级别降级。 3. 自动探测配置方案，如果是纯粹使用javaAPI的方式，则取消日志打印。但是我觉得这样也不靠谱，因为我不确定使用者使用API方案的方式。

2. block后白屏问题，如果因为API不够导致了等待，如果每次都加日志，是不是会日志量过大？另外似乎也不太好加，那里是一个阻塞队列，调用前并不知道队列是否有数据。 这个问题我再想想吧

**Comment by helloworldtang** [comment]
@virjar 
日志是debug级别的，只是在调试期间使用。


项目在正式部署时，至少也应该是info级别的吧

**Comment by helloworldtang** [comment]
现在遇到这样一个现象，项目启动后，过了一会就结束了，也不清楚发生了什么。
log如下

```tex
2017-11-06 18:35:35.277  INFO 23424 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-11-06 18:35:35.278  INFO 23424 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'dataSource' has been autodetected for JMX exposure
2017-11-06 18:35:35.280  INFO 23424 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2017-11-06 18:35:35.395  WARN 23424 --- [           main] c.v.d.c.ippool.config.DungProxyContext   : 没有找到配置文件:proxyclient.properties,代理规则可以通过代码来控制
2017-11-06 18:35:35.396  WARN 23424 --- [           main] c.v.d.c.ippool.config.DungProxyContext   : 没有找到配置文件:proxyclient.properties,代理规则可以通过代码来控制
2017-11-06 18:35:35.402  INFO 23424 --- [           main] c.v.d.c.i.s.impl.JSONFileAvProxyDumper   : json序列化器,文件路径为:F:\project\workspace\spider\target\classes\availableProxy.json
2017-11-06 18:35:35.402  INFO 23424 --- [           main] c.v.d.c.i.s.impl.JSONFileAvProxyDumper   : json序列化器,文件路径为:F:\project\workspace\spider\target\classes\availableProxy.json
2017-11-06 18:35:35.470  INFO 23424 --- [           main] us.codecraft.webmagic.Spider             : Spider zhipin.com started!
2017-11-06 18:36:53.107  INFO 23424 --- [           main] us.codecraft.webmagic.Spider             : Spider zhipin.com closed! 70 pages downloaded.
2017-11-06 18:36:53.108  INFO 23424 --- [           main] c.h.c.databank.spider.SpiderApplication  : Started SpiderApplication in 79.063 seconds (JVM running for 79.4)
2017-11-06 18:36:53.108  INFO 23424 --- [       Thread-5] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@77847718: startup date [Mon Nov 06 18:35:34 CST 2017]; root of context hierarchy
2017-11-06 18:36:53.109  INFO 23424 --- [       Thread-5] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-11-06 18:36:53.109  INFO 23424 --- [       Thread-7] c.v.d.c.i.s.impl.JSONFileAvProxyDumper   : json序列化器,文件路径为:F:\project\workspace\spider\target\classes\availableProxy.json
2017-11-06 18:36:53.110  INFO 23424 --- [       Thread-5] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans

```

**Comment by virjar** [comment]
这个应该不是我这边儿的锅
1. 你的抓取任务是不是本身就比较少，所以刚开始就结束了。
2. 可能是代理IP质量不好，返回了非正常的网页文本，这个时候按照正常网页的抽取规则，是拿不到数据的。这种情况，你需要判断网页是否是预期的，非预期返回需要重试任务，并且以合适的方式处理当前代理IP（惩罚，下线，降分等）

**Comment by helloworldtang** [comment]
在下面的if打了断点，debug时为什么一直没有走到过呢？
```java
                    if (!page.isDownloadSuccess() && StringUtils.contains(page.getRawText(), "请证明你不是机器人")) {
                        avProxy.block(BLOCK_TIME_STAMP_2HOUR);
                    }

```

![dungproxyprovider](https://user-images.githubusercontent.com/13701989/32486391-763bcc48-c3e1-11e7-9a89-d8432861953a.png)

**Comment by helloworldtang** [comment]
@virjar 我的锅。少了这句
```java
IpPoolHolder.init(DungProxyContext.create().setPoolEnabled(true));
```

**Comment by helloworldtang** [comment]
spring boot下报这个错。不是很友好啊

怎么破

```tex
2017-11-07 18:03:02.759  INFO 30976 --- [efresh-thread-1] c.v.d.c.i.s.impl.JSONFileAvProxyDumper   : json序列化器,文件路径为:F:\lagou\file:\F:\lagou\spider-1.0.0.jar!\BOOT-INF\classes!\availableProxy.json
2017-11-07 18:03:02.760 ERROR 30976 --- [efresh-thread-1] c.v.d.c.i.s.impl.JSONFileAvProxyDumper   : error when serialize proxy data

java.io.IOException: can not create directory for file:F:\lagou\file:\F:\lagou\spider-1.0.0.jar!\BOOT-INF\classes!\availableProxy.json
        at com.virjar.dungproxy.client.util.CommonUtil.ensurePathExist(CommonUtil.java:71) ~[dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.ippool.strategy.impl.JSONFileAvProxyDumper.serializeProxy(JSONFileAvProxyDumper.java:52) ~[dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.model.AvProxy.recordProxyChange(AvProxy.java:92) [dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.model.AvProxy.<init>(AvProxy.java:83) [dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.model.AvProxyVO.toModel(AvProxyVO.java:143) [dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.ippool.DomainPool.doRefresh(DomainPool.java:254) [dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.ippool.DomainPool.access$300(DomainPool.java:31) [dungproxy-client-0.0.7.jar!/:na]
        at com.virjar.dungproxy.client.ippool.DomainPool$RefreshThread.run(DomainPool.java:214) [dungproxy-client-0.0.7.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_144]

```

**Comment by virjar** [comment]
spring-boot的问题，是我的锅。项目初期确实没有考虑到这么多情况，没有想到有all-in-one方式运行的case，你可以从新定义这个文件地址。我后续把他弄到临时目录里面去吧。抱歉
